---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: bernieEC2.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-de03c4a2
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - rubbertest_production_default
  - rubbertest_production_web
  external_host: ec2-54-208-215-139.compute-1.amazonaws.com
  external_ip: 54.208.215.139
  internal_host: ip-172-31-35-10.ec2.internal
  internal_ip: 172.31.35.10
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: bernieEC2.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-29564254
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - rubbertest_production_default
  external_host: ec2-54-209-124-218.compute-1.amazonaws.com
  external_ip: 54.209.124.218
  internal_host: ip-172-31-40-11.ec2.internal
  internal_ip: 172.31.40.11
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: bernieEC2.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-4d544030
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - rubbertest_production_default
  external_host: ec2-54-209-108-249.compute-1.amazonaws.com
  external_ip: 54.209.108.249
  internal_host: ip-172-31-38-249.ec2.internal
  internal_ip: 172.31.38.249
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app02
  domain: bernieEC2.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-0ca46170
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - rubbertest_production_default
  external_host: ec2-54-209-142-29.compute-1.amazonaws.com
  external_ip: 54.209.142.29
  internal_host: ip-172-31-39-148.ec2.internal
  internal_ip: 172.31.39.148
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
